First shot at deploying jar from archive

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -88,7 +88,6 @@ commands:
             echo "pipeline.git.branch << pipeline.git.branch >>"
             echo "pipeline.git.revision << pipeline.git.revision >>"
             echo "pipeline.git.base_revision << pipeline.git.base_revision >>"
-      - setup-shared-env
       # For now we are going to hard-code "dev" when we generate config for jar builds
       - render-configs  
       - run:
@@ -140,7 +139,32 @@ commands:
             JAR_BASE_NAME=DataDonationPlatform
             JAR_FILE_NAME="${JAR_BASE_NAME}_${DATE}_${SHORT_GIT_SHA}.jar"
             LOCAL_JAR_FILE_PATH="./target/${JAR_BASE_NAME}.jar"
-            gsutil cp  ${LOCAL_JAR_FILE_PATH} "gs://${BUILDS_BUCKET}/ddp-study-server-pepper-apis/${JAR_FILE_NAME}"                         
+            gsutil cp  ${LOCAL_JAR_FILE_PATH} "gs://${BUILDS_BUCKET}/ddp-study-server-pepper-apis/${JAR_FILE_NAME}"
+  
+  retrieve-jar:
+    steps:
+      - run:
+          name: Retrieve jar from bucket
+          command: |
+            set -u
+            set +e
+            # @TODO remove when done
+            SHORT_GIT_SHA=ae6df4
+            vault read -format=json  secret/pepper/prod/v1/conf | jq -r .data.gcp.serviceKey | gcloud auth activate-service-account --key-file=-
+            JAR_BASE_NAME=DataDonationPlatform
+            JAR_FILE_URL_PATTERN="gs://${BUILDS_BUCKET}/ddp-study-server-pepper-apis/${JAR_BASE_NAME}_*_${SHORT_GIT_SHA}.jar"
+            echo "Checking for ${JAR_FILE_URL_PATTERN}"
+            # For some reason following line generating exit code 1 every time in CircleCI. Use set +e so script can continue
+            JAR_FILE_URL=`gsutil ls $JAR_FILE_URL_PATTERN  | sort -r | head -1`
+            if [ -z $JAR_FILE_URL ]
+              then
+                echo "Could not find archive using pattern ${JAR_FILE_URL_PATTERN}"
+                exit 1
+            fi
+            JAR_FILE_PATH="../target/${JAR_BASE_NAME}.jar"
+            mkdir -p $(dirname $JAR_FILE_PATH)
+            gsutil cp  $JAR_FILE_URL $JAR_FILE_PATH
+
 
   deploy-jar:
     steps:
@@ -168,19 +192,30 @@ jobs:
     executor:
       name: maven-executor
     steps:
+      - setup-shared-env
       - build-jar
 
   build-and-store-jar-job:
     executor:
       name: maven-executor
     steps:
+      - setup-shared-env
       - build-jar
       - store-jar   
+
+  deploy-jar-job:
+    executor:
+      name: maven-executor
+    steps:
+      - setup-shared-env
+      - extract-jar
+      - deploy-jar
 
   build-and-deploy-job:
     executor:
       name: maven-executor
     steps:
+      - setup-shared-env
       - build-jar
       - deploy-jar      
 
@@ -188,7 +223,7 @@ workflows:
   version: 2
   build-deploy:
     jobs:
-      - build-and-store-jar-job:
+      - deploy-jar-job:
           filters:
             branches:
               only: study-server-to-appengine
