Tcell instrumentation (#180)
Added tcell agent

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,6 +1,11 @@
 version: 2.1
 
 references:
+  tcell_dir: &tcell_dir
+             tcell
+  # to install a new version of tcell, do  "tar -cvfz tcell-x.y.z.tar.gz tcell" after expanding tcell's zip
+  tcell_gcp_path: &tcell_gcp_path
+                  gs://ddp-tcell/tcell-1.10.0.tar.gz
   ci_support_image: &ci_support_image
                        broadinstitute/study-server-build:2020-04-10G
   root_path: &root_path
@@ -32,9 +37,6 @@ references:
 
 
 executors:
-  build-executor:
-    docker:
-      - image: broadinstitute/study-server-build:java-2020-04-15A
   test-executor:
     docker:
       - image: broadinstitute/study-server-build:java-2020-04-20A
@@ -53,6 +55,29 @@ executors:
     - image: *ci_support_image
 
 commands:
+  install-tcell:
+    parameters:
+      tcell_gcp_path:
+        type: string
+        default: *tcell_gcp_path
+    steps:
+      - run:
+          name: Download tcell files from bucket
+          command: |
+            TCELL_GCP_PATH='<<parameters.tcell_gcp_path>>'
+            vault read -format=json  secret/pepper/prod/v1/conf | jq -r .data.gcp.serviceKey | gcloud auth activate-service-account --key-file=-
+            TAR_FILE_URL=`gsutil ls $TCELL_GCP_PATH | sort -r | head -1`
+
+            if [ -z $TAR_FILE_URL ]
+            then
+              echo "Could not find tcell archive ${TCELL_GCP_PATH}"
+              exit 1
+            fi
+            TAR_FILE_PATH="/tmp/$(basename -- $TAR_FILE_URL)"
+            gsutil cp  $TAR_FILE_URL $TAR_FILE_PATH
+
+            # untarring will create a "tcell" dir
+            tar --no-same-owner -xvf $TAR_FILE_PATH
   build-jar:
     description: Build jar
     parameters:
@@ -91,6 +116,9 @@ commands:
               study-server-parallel-tests)
               DEPLOY_ENV=dev
             ;;
+              tcell-instrumentation)
+              DEPLOY_ENV=dev
+            ;;
             test)
               DEPLOY_ENV=test
             ;;
@@ -110,7 +138,7 @@ commands:
             esac
             echo "Setting deployment ENVIRONMENT to $DEPLOY_ENV"
             echo "export ENVIRONMENT=$DEPLOY_ENV" >> $BASH_ENV
-            source $BASH_ENV          
+            source $BASH_ENV
 
   render-configs:
     description: render config files
@@ -143,7 +171,7 @@ commands:
             mysql -h 127.0.0.1 -u root --password=$MYSQL_ROOT_PASSWORD test_db --execute="CREATE DATABASE << parameters.studyserverdb >> CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"
             mysql -h 127.0.0.1 -u root --password=$MYSQL_ROOT_PASSWORD test_db --execute="CREATE DATABASE << parameters.housekeepingdb >> CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"
           environment: *DB_VARS
-    
+
   show-pipeline-vars:
     description: "Show pipeline vars"
     steps:
@@ -186,7 +214,7 @@ commands:
             JAR_BUCKET_URL="gs://${BUILDS_BUCKET}${JAR_BUILD_BUCKET_DIR}/${JAR_FILE_NAME}"
             gsutil cp "${LOCAL_JAR_FILE_PATH}" "${JAR_BUCKET_URL}"
             echo "${JAR_FILE_NAME} successfully uploaded to ${JAR_BUCKET_URL}"
-  
+
   retrieve-jar:
     description: Get <<parameters.jar_base_name>> jar from bucket
     parameters:
@@ -229,16 +257,23 @@ commands:
       deploy_dir:
         type: string
         default: deployment-assets
+      tcell_dir:
+        type: string
+        default: *tcell_dir
     steps:
       - set-deployment-env
       - render-configs
+      - install-tcell
       - run:
           name: Gather deployment assets
           command: |
             DEPLOY_DIR='<<parameters.deploy_dir>>'
+            TCELL_DIR='<<parameters.tcell_dir>>'
             rm -rf $DEPLOY_DIR
             mkdir -p $DEPLOY_DIR
             cd $DEPLOY_DIR
+            cp -r ../$TCELL_DIR .
+            cp ../output-config/tcell_agent.config $TCELL_DIR
             cp ../target/<<parameters.jar_base_name>>.jar .
             cp ../src/appengine/<<parameters.jar_base_name>>.yaml .
             cp ../output-config/application.conf .
@@ -565,7 +600,7 @@ jobs:
       - retrieve-jar:
           jar_base_name: Housekeeping
       - deploy-jar:
-          jar_base_name: Housekeeping    
+          jar_base_name: Housekeeping
 
 parameters:
   on_demand:
@@ -586,6 +621,7 @@ workflows:
                 - &rc /^rc.*/
                 - &hotfix /^hotfix.*/
                 - study-server-parallel-tests
+                - tcell-instrumentation
       - parallel-compile-and-test-job:
           parallelism: *test_parallelism
           <<: *compile_and_test_filters
@@ -595,6 +631,7 @@ workflows:
               only:
                 - develop
                 - study-server-parallel-tests
+                - tcell-instrumentation
           requires:
             - parallel-compile-and-test-job
             - compile-and-run-test-suite-job
@@ -605,6 +642,7 @@ workflows:
                 - *rc
                 - *hotfix
                 - study-server-parallel-tests
+                - tcell-instrumentation
           requires:
             - compile-and-run-test-suite-job
             - parallel-compile-and-test-job
@@ -627,6 +665,5 @@ workflows:
                 - production
                 # @todo remove when done
                 - test_deleteme1
-
 
 
